# Generated by Django 5.1.4 on 2025-01-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_categoria_cliente_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
